package: openapi
output: ../app/transports/http/openapi/server_gen.go
output-options:
  nullable-type: true
generate:
  client: true
  echo-server: true
  strict-server: true
  models: true
  embedded-spec: true
